apiVersion: batch/v1
kind: CronJob
metadata:
  name: leveldb-backup-secure
  namespace: leveldb
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-sa
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: backup
            image: restic/restic:latest
            command: ["/bin/sh", "/scripts/backup-secure.sh"]
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
              seccompProfile:
                type: RuntimeDefault
            volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: leveldb-data
              mountPath: /data/leveldb
              readOnly: true
            - name: backup-storage
              mountPath: /backup
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: AWS_DEFAULT_REGION
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: RESTIC_PASSWORD
            - name: RESTIC_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: restic-secret
                  key: RESTIC_REPOSITORY
          restartPolicy: OnFailure
          volumes:
          - name: scripts
            configMap:
              name: restic-scripts
          - name: leveldb-data
            persistentVolumeClaim:
              claimName: leveldb-storage-leveldb-0
          - name: backup-storage
            emptyDir: {} 