apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: leveldb-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: LevelDBAlerts
    rules:
    - alert: LevelDBPodCrashLoop
      expr: increase(kube_pod_container_status_restarts_total{namespace="leveldb",pod=~"leveldb.*"}[5m]) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "LevelDB pod is restarting too frequently"
        description: "LevelDB pod {{ $labels.pod }} has restarted more than 3 times in the last 5 minutes"

    - alert: LevelDBPVC80PercentFull
      expr: (kubelet_volume_stats_used_bytes{namespace="leveldb"} / kubelet_volume_stats_capacity_bytes{namespace="leveldb"}) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "LevelDB PVC is more than 80% full"
        description: "PersistentVolumeClaim {{ $labels.persistentvolumeclaim }} is reaching storage capacity"

    - alert: LevelDBPodDown
      expr: up{namespace="leveldb",job="leveldb-monitor"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "LevelDB pod is down"
        description: "LevelDB pod {{ $labels.pod }} is not responding to health checks"

    - alert: LevelDBHighMemoryUsage
      expr: (container_memory_usage_bytes{namespace="leveldb",container="leveldb"} / container_spec_memory_limit_bytes{namespace="leveldb",container="leveldb"}) > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "LevelDB pod memory usage is high"
        description: "LevelDB pod {{ $labels.pod }} is using more than 85% of memory limit"

    - alert: LevelDBHighCPUUsage
      expr: (rate(container_cpu_usage_seconds_total{namespace="leveldb",container="leveldb"}[5m]) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "LevelDB pod CPU usage is high"
        description: "LevelDB pod {{ $labels.pod }} is using more than 80% CPU"

    - alert: BackupJobFailed
      expr: kube_job_status_failed{namespace="leveldb",job=~"leveldb-backup.*"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "LevelDB backup job failed"
        description: "Backup job {{ $labels.job }} has failed"
