apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: leveldb-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: leveldb
  namespaceSelector:
    matchNames:
    - leveldb
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s 