apiVersion: apps/v1
kind: Deployment
metadata:
  name: leveldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leveldb
  template:
    metadata:
      labels:
        app: leveldb
    spec:
      containers:
      - name: leveldb
        image: fayyazgt/leveldb-api:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: leveldb-storage
          mountPath: /data/leveldb
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: leveldb-storage
        persistentVolumeClaim:
          claimName: leveldb-pvc
